#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : requests-ntlm
Version  : 1.1.0
Release  : 4
URL      : https://github.com/requests/requests-ntlm/archive/v1.1.0.tar.gz
Source0  : https://github.com/requests/requests-ntlm/archive/v1.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: requests-ntlm-python3
Requires: requests-ntlm-license
Requires: requests-ntlm-python
Requires: cryptography
Requires: ntlm-auth
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : ntlm-auth
BuildRequires : requests

%description
requests-ntlm
=============
.. image:: https://travis-ci.org/requests/requests-ntlm.svg?branch=master
:target: https://travis-ci.org/requests/requests-ntlm

%package license
Summary: license components for the requests-ntlm package.
Group: Default

%description license
license components for the requests-ntlm package.


%package python
Summary: python components for the requests-ntlm package.
Group: Default
Requires: requests-ntlm-python3

%description python
python components for the requests-ntlm package.


%package python3
Summary: python3 components for the requests-ntlm package.
Group: Default
Requires: python3-core

%description python3
python3 components for the requests-ntlm package.


%prep
%setup -q -n requests-ntlm-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534442724
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/requests-ntlm
cp LICENSE %{buildroot}/usr/share/doc/requests-ntlm/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/requests-ntlm/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
